services:

  db:
    image: postgres:17
    container_name: bot_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nelenkin_club
    ports:
      - 5432:5432
