"""Initial commit

Revision ID: 05a1bcfb8c89
Revises: 
Create Date: 2025-07-11 15:18:38.419947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a1bcfb8c89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contribution_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_type_name', sa.Text(), nullable=False),
    sa.Column('contribution_type_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Contribution_type_pkey'),
    if_not_exists=True
    )
    op.create_table('Contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('contribution_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='Contributions_pkey'),
    if_not_exists=True
    )
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Course_pkey'),
    if_not_exists=True
    )
    op.create_table('Enrollments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('Membership_granted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_granted', sa.Date(), nullable=False),
    sa.Column('days_granted', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Membership_granted_pkey'),
    if_not_exists=True
    )
    op.create_table('Users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_joined', sa.JSON(), nullable=True),
    sa.Column('date_membership_started', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Membership_granted')
    op.drop_table('Enrollments')
    op.drop_table('Course')
    op.drop_table('Contributions')
    op.drop_table('Contribution_type')
    # ### end Alembic commands ###
