"""Add course, contributions, contributions type, membership granted

Revision ID: 226694af376d
Revises: d830617bc3df
Create Date: 2025-07-11 15:07:38.450540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226694af376d'
down_revision: Union[str, Sequence[str], None] = 'd830617bc3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contribution_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_type_name', sa.Text(), nullable=False),
    sa.Column('contribution_type_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Contribution_type_pkey')
    )
    op.create_table('Contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('contribution_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='Contributions_pkey')
    )
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Course_pkey')
    )
    op.create_table('Membership_granted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_granted', sa.Date(), nullable=False),
    sa.Column('days_granted', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Membership_granted_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Membership_granted')
    op.drop_table('Course')
    op.drop_table('Contributions')
    op.drop_table('Contribution_type')
    # ### end Alembic commands ###
