"""add a list for language options

Revision ID: 47ccc3189882
Revises: f7c1e3515877
Create Date: 2026-08-24 01:49:07.143675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ccc3189882'
down_revision: Union[str, Sequence[str], None] = 'f7c1e3515877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MockSignUp', sa.Column('language_options', sa.JSON(), nullable=True))
    op.alter_column('MockSignUp', 'english_choice',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MockSignUp', 'english_choice',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('MockSignUp', 'language_options')
    # ### end Alembic commands ###
