"""add table for membership because of activity

Revision ID: fab91702602c
Revises: fcfbd017c142
Create Date: 2025-10-23 16:58:44.381552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab91702602c'
down_revision: Union[str, Sequence[str], None] = 'fcfbd017c142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MembershipByActivity',
    sa.Column('tg_id', sa.Text(), nullable=False),
    sa.Column('tg_username', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['Users.tg_id'], name='fk_valid_tg_id'),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MembershipByActivity')
    # ### end Alembic commands ###
